default:
  theme: modern
  content_css: "<%= asset_path('tinymce-content.css') %>"
  plugins: "lists anchor contextmenu image link table"
  contextmenu: "link image inserttable | cell row column deletetable"
  toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons"
